server {
    server_name paimini.mianmiannb666.com;

    root /var/www/paimini;
    index index.html;

    location ~ \.mjs$ {
        default_type application/javascript;
        try_files $uri =404;
    }

    location ^~ /npm/ {
        proxy_pass https://cdn.jsdelivr.net;
        proxy_ssl_server_name on;
        proxy_set_header Host cdn.jsdelivr.net;
    }

    location ^~ /npm2/ {
        proxy_pass https://cdn.jsdelivr.net/npm/;
        proxy_ssl_server_name on;
        proxy_set_header Host cdn.jsdelivr.net;
        proxy_hide_header Cache-Control;
        add_header Cache-Control "no-store, max-age=0" always;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/paimini.mianmiannb666.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/paimini.mianmiannb666.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = paimini.mianmiannb666.com) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name paimini.mianmiannb666.com;
    return 404;
}
